name: Primeriti Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual run

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      MAIN_BOT_TOKEN: ${{ secrets.MAIN_BOT_TOKEN }}
      MAIN_CHAT_ID: ${{ secrets.MAIN_CHAT_ID }}
      DEBUG_BOT_TOKEN: ${{ secrets.DEBUG_BOT_TOKEN }}
      DEBUG_CHAT_ID: ${{ secrets.DEBUG_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache hashes
        uses: actions/cache@v3
        with:
         path: hashes
         key: ${{ runner.os }}-primeriti-hashes-${{ hashFiles('hashes/**') }}
         restore-keys: |
          ${{ runner.os }}-primeriti-hashes-

      - name: Run monitoring script
        run: python primeriti_monitor.py

      # Set up Git configuration
      - name: Set up Git configuration
        run: |
         git config --global user.name "GitHub Actions"
         git config --global user.email "actions@github.com"

      # Commit and push changes to the hashes directory
      - name: Commit and push changes
        run: |
          git add -f hashes/
          git commit -m "Update hashes" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PRIMERITI_TOKEN }}@github.com/david-garcia-martin/prim-monitor.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.PRIMERITI_TOKEN }}
